# Exported from Render on 2025-05-01T07:17:30Z
services:
- type: web
  name: rails-user-render
  runtime: ruby
  repo: https://github.com/5hado/sa19-act2-try2
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: RAILS_ENV
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
