default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>

cable:
  production:
    <<: *default
    database: <%= ENV['CABLE_DATABASE_URL'] %>
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>
