default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: board_game_library_development
  username: <%= ENV.fetch("PG_USERNAME", "your_db_username") %>
  password: <%= ENV.fetch("PG_PASSWORD", "your_db_password") %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: board_game_library_test
  username: <%= ENV.fetch("PG_USERNAME", "your_db_username") %>
  password: <%= ENV.fetch("PG_PASSWORD", "your_db_password") %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>

cable:
  production:
    <<: *default
    database: <%= ENV['CABLE_DATABASE_URL'] %>
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>
